#pragma once
#include <string.h>  /* memset */ 
#include <stdlib.h>
#define IMD2000_MAX_TARGETS  (20)  

//typedef unsigned char  uint8_t; 
//typedef unsigned int uint16_t; 
typedef int sint16_t; 
//typedef unsigned long uint32_t; 
typedef long sint32_t; 
typedef float float32_t;

typedef struct
{
    float32_t f32_range_m;
    float32_t f32_velocity_mps;
    float32_t f32_signal_dB;
    float32_t f32_estimatedTimeOfArrival_s;

}IMD2000_Target_t; 
 
typedef struct { 
    uint16_t ui16_nrOfTargets; 
    uint16_t ui16_targetListId; 
    uint16_t ui16_blockageDetection; 
    uint16_t ui16_reserved; 
    IMD2000_Target_t target[IMD2000_MAX_TARGETS]; 
}IMD2000_TargetList_t; 

typedef enum { 
    IMD2000_API_ERR_OK  = 0x0000, 
    IMD2000_API_ERR_FUNCTION_DEPRECATED, 
    IMD2000_API_ERR_DLL_NOT_FINISHED, 
    IMD2000_API_ERR_HANDLE_NOT_INITIALIZED, 
    IMD2000_API_ERR_COMPORT_DOESNT_EXIST, 
    IMD2000_API_ERR_COMPORT_CANT_INITIALIZE, 
    IMD2000_API_ERR_COMPORT_ACCESS_DENIED, 
    IMD2000_API_ERR_COMPORT_BAUDRATE_NOT_VALID, 
    IMD2000_API_ERR_COMPORT_CANT_OPEN  , 
    IMD2000_API_ERR_COMPORT_CANT_SET_FLOW_CONTROL, 
    IMD2000_API_ERR_COMPORT_CANT_SET_PARITY, 
    IMD2000_API_ERR_COMPORT_CANT_SET_STOP_BITS, 
    IMD2000_API_ERR_COMPORT_CANT_SET_DATA_BITS, 
    IMD2000_API_ERR_COMPORT_CANT_SET_BAUDRATE, 
    IMD2000_API_ERR_COMPORT_ALREADY_INITIALIZED , 
    IMD2000_API_ERR_COMPORT_EQUALS_NULL, 
    IMD2000_API_ERR_COMPORT_NOT_OPEN , 
    IMD2000_API_ERR_COMPORT_NOT_READABLE , 
    IMD2000_API_ERR_COMPORT_NOT_WRITEABLE  , 
    IMD2000_API_ERR_COMPORT_CANT_WRITE   , 
    IMD2000_API_ERR_COMPORT_CANT_READ  , 
    IMD2000_API_ERR_COMMAND_NOT_WRITTEN  , 
    IMD2000_API_ERR_COMMAND_NOT_READ  , 
    IMD2000_API_ERR_COMMAND_NO_DATA_RECEIVED, 
    IMD2000_API_ERR_COMMAND_NO_VALID_FRAME_FOUND, 
    IMD2000_API_ERR_COMMAND_RX_FRAME_DAMAGED, 
    IMD2000_API_ERR_COMMAND_FAILURE, 
    IMD2000_API_ERR_UNDEFINED_READ  , 
    IMD2000_API_ERR_COMPORT_LESS_DATA_READ , 
    IMD2000_API_ERR_COMPORT_SYSTEM_INIT_FAILED, 
    IMD2000_API_ERR_COMPORT_SYSTEM_ALREADY_INITIALIZED , 
    IMD2000_API_ERR_COMMAND_RX_FRAME_LENGTH, 
    IMD2000_API_ERR_COMMAND_MAX_DATA_OVERFLOW, 
    IMD2000_API_ERR_COMMAND_MAX_IQPAIRS_OVERFLOW, 
    IMD2000_API_ERR_COMMAND_NOT_ACCEPTED, 
    IMD2000_API_ERR_NULL_POINTER , 
    IMD2000_API_ERR_PARAMETER_OUT_OF_RANGE , 
    IMD2000_API_ERR_COMMAND_UNEXPECTED_FRAMETYPE, 
IMD2000_API_ERR_COMMAND_WITH_FAILURE_CODE} 
IMD2000_Result_t; 
 
 IMD2000_Result_t IMD2000_decodeTargetFrame(unsigned char *frame_array,IMD2000_TargetList_t *targetList); 